attribute = { fg = "#727272" }
comment = { fg = "#474747", modifiers = ["italic"] }
"comment.block.documentation" = 
constant = { fg = "#aaaaaa" }
"constant.builtin" = { fg = "#7a7a7a" }
"constant.builtin.boolean" = { fg = "#66b2b2" }
"constant.character" = { fg = "#aaaaaa" }
"constant.character.escape" = { fg = "#708090" }
"constant.numeric" = { fg = "#aaaaaa" }
"constant.numeric.float" = { fg = "#aaaaaa" }
"constant.numeric.integer" = { fg = "#aaaaaa" }
constructor = { fg = "#aaaaaa" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = 
"diff.delta.moved" = 
"diff.minus" = 
"diff.plus" = 
error = { fg = "#ffc0b9" }
function = { fg = "#cccccc", modifiers = ["bold"] }
"function.builtin" = { fg = "#646464" }
"function.macro" = { fg = "#727272", modifiers = ["bold"] }
"function.method" = { fg = "#cccccc" }
"function.special" = { fg = "#727272", modifiers = ["bold"] }
hint = { fg = "#deeeed" }
info = { fg = "#8cf8f7" }
keyword = { fg = "#727272" }
"keyword.control" = { fg = "#727272", modifiers = ["bold"] }
"keyword.control.conditional" = { fg = "#727272", modifiers = ["bold"] }
"keyword.control.exception" = { fg = "#727272", modifiers = ["bold"] }
"keyword.control.repeat" = { fg = "#727272", modifiers = ["bold"] }
"keyword.control.return" = { fg = "#6c6c6c", modifiers = ["bold"] }
"keyword.directive" = { fg = "#727272", modifiers = ["bold"] }
"keyword.function" = 
"keyword.operator" = { fg = "#727272", modifiers = ["bold"] }
label = { fg = "#7a7a7a" }
"markup.bold" = 
"markup.heading" = { fg = "#7a7a7a" }
"markup.heading.completion" = { bg = "#191919", fg = "#cccccc" }
"markup.heading.hover" = { bg = "#1bfd9c", fg = "#0d0d0d", modifiers = ["bold"] }
"markup.italic" = 
"markup.link" = { fg = "#7a7a7a" }
"markup.link.label" = { fg = "#f1f1f1" }
"markup.link.text" = { fg = "#7a7a7a" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#444444" }
"markup.normal.completion" = 
"markup.normal.hover" = 
"markup.raw" = { fg = "#aaaaaa" }
"markup.raw.inline" = 
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#727272", modifiers = ["bold"] }
operator = { fg = "#1bfd9c", modifiers = ["bold"] }
special = { fg = "#f1f1f1" }
string = { fg = "#aaaaaa" }
"string.regexp" = { fg = "#708090" }
"string.special" = { fg = "#708090" }
tag = { fg = "#aaaaaa" }
type = { fg = "#aaaaaa" }
"type.builtin" = { fg = "#aaaaaa" }
"type.enum" = { fg = "#aaaaaa" }
"type.enum.variant" = { fg = "#aaaaaa" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#cccccc", fg = "#101010" }
"ui.cursor.match" = { fg = "#1bfd9c", modifiers = ["bold"] }
"ui.linenr" = { fg = "#444444" }
"ui.linenr.select" = { fg = "#aaaaaa" }
"ui.menu" = { bg = "#191919", fg = "#cccccc" }
"ui.menu.scroll" = { bg = 2763306, fg = 5592405 }
"ui.menu.selected" = { bg = "#1bfd9c", fg = "#0d0d0d", modifiers = ["bold"] }
"ui.popup" = { fg = "#444444" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#161616", fg = "#7a7a7a" }
"ui.statusline.inactive" = { bg = "#161616", fg = "#444444" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#101010", fg = "#cccccc" }
"ui.text.focus" = { bg = "#282828" }
"ui.text.inactive" = { fg = "#474747", modifiers = ["italic"] }
"ui.text.info" = { fg = "#cccccc" }
"ui.virtual.inlay-hint" = { bg = "#252626", fg = "#deeeed" }
"ui.window" = { fg = "#444444" }
variable = { fg = "#cccccc" }
"variable.builtin" = { fg = "#6f6f6f" }
"variable.other.member" = { fg = "#aaaaaa" }
"variable.parameter" = { fg = "#8e8e8e" }
warning = { fg = "#fce094" }

[palette]
bg = "#101010"
bg_menu = "#191919"
bg_popup = "#181818"
bg_statusline = "#161616"
black = "#0d0d0d"
blue1 = "#b2d8d8"
blue2 = "#66b2b2"
border = "#444444"
"cmp.deprecated" = "#444444"
"cmp.kind" = "#aaaaaa"
"cmp.snippet" = "#708090"
cur_line = "#1f1f1f"
cur_line_nr = "#aaaaaa"
"diff.add" = "#769f7f"
"diff.change" = "#7a7a7a"
"diff.delete" = "#9f7276"
"diff.text" = "#555555"
error = "#ffc0b9"
fg = "#cccccc"
fg_gutter = "#444444"
fg_sidebar = "#7a7a7a"
"fs.binary_data" = "#7a7a7a"
"fs.dir" = "#aaaaaa"
"fs.exec" = "#66b2b2"
"fs.file" = "#cccccc"
"fs.link" = "#deeeed"
"fs.socket" = "#7a7a7a"
"git.add" = "#baffc9"
"git.change" = "#ffffba"
"git.delete" = "#ffb3ba"
glow = "#1bfd9c"
gray1 = "#080808"
gray10 = "#f1f1f1"
gray2 = "#191919"
gray3 = "#2a2a2a"
gray4 = "#444444"
gray5 = "#555555"
gray6 = "#7a7a7a"
gray7 = "#aaaaaa"
gray8 = "#cccccc"
gray9 = "#dddddd"
hint = "#deeeed"
icon = "#7a7a7a"
info = "#8cf8f7"
lack = "#708090"
light_blue = "#a6dbff"
light_cyan = "#8cf8f7"
light_green = "#b3f6c0"
light_magenta = "#ffcaff"
light_red = "#ffc0b9"
light_yellow = "#fce094"
lsp_ref = "#242424"
luster = "#deeeed"
"mode.command.bg" = "#1bfd9c"
"mode.command.fg" = "#0d0d0d"
"mode.insert.bg" = "#1bfd9c"
"mode.insert.fg" = "#0d0d0d"
"mode.normal.bg" = "#111111"
"mode.normal.fg" = "#cccccc"
"mode.replace.bg" = "#dddddd"
"mode.replace.fg" = "#0d0d0d"
"mode.visual.bg" = "#dddddd"
"mode.visual.fg" = "#0d0d0d"
ok = "#b3f6c0"
selection = "#1f1f1f"
"special.comment" = "#474747"
"special.exception" = "#505050"
"special.keyword" = "#727272"
"special.param" = "#8e8e8e"
"special.property" = "#8b8b8b"
"special.whitespace" = "#202020"
"syntax.boolean" = "#66b2b2"
"syntax.builtin" = "#646464"
"syntax.comment" = "#474747"
"syntax.const" = "#aaaaaa"
"syntax.const_builtin" = "#7a7a7a"
"syntax.func_call" = "#7a7a7a"
"syntax.func_def" = "#cccccc"
"syntax.func_param" = "#8e8e8e"
"syntax.keyword" = "#727272"
"syntax.keyword_exception" = "#505050"
"syntax.keyword_return" = "#6c6c6c"
"syntax.property" = "#8b8b8b"
"syntax.punctuation" = "#cccccc"
"syntax.special" = "#f1f1f1"
"syntax.string" = "#aaaaaa"
"syntax.string_escape" = "#708090"
"syntax.tag" = "#aaaaaa"
"syntax.type" = "#aaaaaa"
"syntax.type_def" = "#cccccc"
"syntax.type_primitive" = "#aaaaaa"
"syntax.var" = "#cccccc"
"syntax.var_builtin" = "#6f6f6f"
"syntax.var_member" = "#aaaaaa"
"terminal.black" = "#2a2a2a"
"terminal.black_bright" = "#4a4a4a"
"terminal.blue" = "#7a7a7a"
"terminal.blue_bright" = "#aaaaaa"
"terminal.cyan" = "#cccccc"
"terminal.cyan_bright" = "#d3d3d3"
"terminal.green" = "#1bfd9c"
"terminal.green_bright" = "#a6ffc9"
"terminal.magenta" = "#66b2b2"
"terminal.magenta_bright" = "#49c4c4"
"terminal.red" = "#deeeed"
"terminal.red_bright" = "#708090"
"terminal.white" = "#f1f1f1"
"terminal.white_bright" = "#ffffff"
"terminal.yellow" = "#b4b4b4"
"terminal.yellow_bright" = "#dddddd"
title = "#7a7a7a"
todo = "#708090"
visual = "#282828"
warning = "#fce094"
white = "#ffffff"